# -*- coding: utf-8 -*-
"""Price Optimization using Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHr77eX23eRQXPOe2XVtwXAzbPMvmcNn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/content/Competition_Data.csv")

print(data.head())

data.info()

"""Now, let’s start by comparing the price distribution with the competition"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.hist(data['Price'], bins=30, alpha=0.7, label='Your Store')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.title('Price Distribution - Your Store')

plt.subplot(1, 2, 2)
plt.hist(data['Competition_Price'], bins=30, alpha=0.7, color='orange', label='Competition')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.title('Price Distribution - Competition')

plt.tight_layout()
plt.show()

"""It shows that the competition’s prices are generally higher, with peaks around the 100-150 and 200-250 price ranges, which indicate a concentration of higher-priced items. In contrast, our store’s prices are more evenly distributed across the 50-300 range, with notable peaks around 100-150.

Now, let’s compare the relationship between price and sales
"""

plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
plt.scatter(data['Price'], data['Sales_Amount'], alpha=0.6, label='Your Store')
plt.xlabel('Price')
plt.ylabel('Sales Amount')
plt.title('Price vs Sales Amount - Our Store')

plt.subplot(1, 2, 2)
plt.scatter(data['Competition_Price'], data['Sales_Amount'], alpha=0.6, color='orange', label='Competition')
plt.xlabel('Competition Price')
plt.ylabel('Sales Amount')
plt.title('Competition Price vs Sales Amount')

plt.tight_layout()
plt.show()

"""The scatter plots illustrate the relationship between price and sales amount for our store (left) and for the competition (right). In our store’s plot, sales amounts are widely scattered across different price points, indicating inconsistent performance across various price ranges and no obvious pattern. On the other hand, the competition’s plot reveals a tight cluster of higher sales amounts, with prices covering a similar range but showing more uniform sales performance. This suggests that the competition may employ a more effective pricing strategy, enabling them to sustain higher sales amounts consistently across different price points.

Now, let’s compare the price changes over time
"""

data['Fiscal_Week_ID'] = pd.to_datetime(data['Fiscal_Week_ID'] + '-1', format='%Y-%U-%w')

weekly_prices = data.groupby('Fiscal_Week_ID').agg({
    'Price': 'mean',
    'Competition_Price': 'mean'
}).reset_index()

plt.figure(figsize=(12, 6))

plt.plot(weekly_prices['Fiscal_Week_ID'], weekly_prices['Price'], label='Our Store', marker='o')
plt.plot(weekly_prices['Fiscal_Week_ID'], weekly_prices['Competition_Price'], label='Competition', marker='o', color='orange')

plt.xlabel('Fiscal Week')
plt.ylabel('Average Price')
plt.title('Price Changes Over Time')
plt.legend()
plt.grid(True)
plt.show()

"""The competition consistently keeps their average prices above 170, showing a gentle upward trend over the weeks observed. In comparison, our store’s prices begin near 166, rise slightly, then decrease before climbing again. This pattern suggests that the competition uses a steadier pricing strategy, whereas our store’s pricing is more variable. The competition’s price stability may be a factor in their stronger and more consistent sales performance.

Now, let’s analyze how changes in prices affect the change in quantity sold.
"""

data['price_change'] = data['Price'].pct_change()
data['qty_change'] = data['Item_Quantity'].pct_change()

data['elasticity'] = data['qty_change'] / data['price_change']

data.replace([float('inf'), -float('inf')], float('nan'), inplace=True)
data.dropna(subset=['elasticity'], inplace=True)

plt.figure(figsize=(12, 6))
plt.plot(data['Fiscal_Week_ID'], data['elasticity'], marker='o', linestyle='-', color='purple')
plt.axhline(0, color='grey', linewidth=0.8)
plt.xlabel('Fiscal Week')
plt.ylabel('Price Elasticity of Demand')
plt.title('Price Elasticity of Demand Over Time')
plt.grid(True)
plt.show()

"""The graph illustrates how the price elasticity of demand changes over time, revealing substantial fluctuations from week to week. Elasticity values range from highly negative to highly positive, indicating that the responsiveness of quantity demanded to price changes varies greatly. In weeks with high positive elasticity, demand rose sharply alongside price increases, whereas weeks with high negative elasticity saw demand fall steeply when prices went up. This wide range of elasticity values suggests that demand does not respond to price changes in a consistent manner. It also implies that other factors—such as promotions, seasonal trends, or broader market conditions—may be significantly impacting demand."""

total_sales_your_store = data['Sales_Amount'].sum()
total_sales_competition = (data['Competition_Price'] * data['Item_Quantity']).sum()

total_qty_your_store = data['Item_Quantity'].sum()
total_qty_competition = data['Item_Quantity'].sum()  # assuming quantities sold are the same for comparison

summary = pd.DataFrame({
    'Metric': ['Total Sales Amount', 'Total Quantity Sold'],
    'Your Store': [total_sales_your_store, total_qty_your_store],
    'Competition': [total_sales_competition, total_qty_competition]
})


summary

# define price brackets
bins = [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
labels = ['0-50', '51-100', '101-150', '151-200', '201-250', '251-300', '301-350', '351-400', '401-450', '451-500']

# create price brackets for both your store and competition
data['price_bracket'] = pd.cut(data['Price'], bins=bins, labels=labels, right=False)
data['competition_price_bracket'] = pd.cut(data['Competition_Price'], bins=bins, labels=labels, right=False)

# calculate sales amount by price bracket for your store
sales_by_bracket_your_store = data.groupby('price_bracket')['Sales_Amount'].sum().reset_index()
sales_by_bracket_your_store.columns = ['Price Bracket', 'Your Store Sales Amount']

# calculate sales amount by price bracket for competition
data['competition_sales_amt'] = data['Competition_Price'] * data['Item_Quantity']
sales_by_bracket_competition = data.groupby('competition_price_bracket')['competition_sales_amt'].sum().reset_index()
sales_by_bracket_competition.columns = ['Price Bracket', 'Competition Sales Amount']

sales_by_bracket = pd.merge(sales_by_bracket_your_store, sales_by_bracket_competition, on='Price Bracket')

sales_by_bracket

"""0-50 Bracket: The competition has significantly higher sales in this bracket.

51-100 Bracket: The competition outperforms our store by a wide margin.

101-150 Bracket: The competition’s sales are much higher than our store’s sales.

151-200 Bracket: The competition again has significantly higher sales.

201-250 Bracket: The competition’s sales are nearly double those of our store.

251-300 Bracket: The competition has higher sales, but the gap is smaller compared to other brackets.

301-350 Bracket: The competition has higher sales, though the overall sales amount is lower in this bracket compared to others.

**Price Optimization with Dynamic Pricing**

Now, let’s start by defining a dynamic pricing model and simulating its performance. Here are the steps we will use:

1) We will enhance our dataset to include segments and calculate price elasticity for each segment.

2) We’ll create segments based on purchasing behaviour and calculate price elasticity for each segment.

3) We’ll define dynamic pricing rules based on competitor pricing, demand, and elasticity.

4) We’ll simulate the dynamic pricing model and compare it with the existing pricing strategy.
"""

# segment customers based on purchasing behavior

# calculate average price and total quantity sold for each item
item_summary = data.groupby('Item_ID').agg({
    'Price': 'mean',
    'Item_Quantity': 'sum'
}).reset_index()

# merge the item summary back to the main dataset
data = pd.merge(data, item_summary, on='Item_ID', suffixes=('', '_avg'))

# define segments based on average price
data['segment'] = pd.cut(data['Price_avg'], bins=[0, 50, 150, 300], labels=['Low', 'Medium', 'High'])

# calculate price elasticity for each segment
segments = data['segment'].unique()
elasticity_data = []

for segment in segments:
    segment_data = data[data['segment'] == segment]
    segment_data['price_change'] = segment_data['Price'].pct_change()
    segment_data['qty_change'] = segment_data['Item_Quantity'].pct_change()
    segment_data['elasticity'] = segment_data['qty_change'] / segment_data['price_change']
    segment_data.replace([float('inf'), -float('inf')], float('nan'), inplace=True)
    avg_elasticity = segment_data['elasticity'].mean()
    elasticity_data.append({'segment': segment, 'avg_elasticity': avg_elasticity})

elasticity_df = pd.DataFrame(elasticity_data)

elasticity_df

"""Now let’s implement a dynamic pricing model by adjusting prices based on elasticity and simulating the impact on sales and revenue"""

# create a copy of the dataset for simulation
dynamic_pricing_data = data.copy()

# apply dynamic pricing rules
dynamic_pricing_data.loc[dynamic_pricing_data['segment'] == 'Medium', 'dynamic_price'] = dynamic_pricing_data['Price'] * 1.05
dynamic_pricing_data.loc[dynamic_pricing_data['segment'] == 'High', 'dynamic_price'] = dynamic_pricing_data['Price'] * 0.90

# calculate new sales amounts based on dynamic prices
dynamic_pricing_data['dynamic_sales_amt'] = dynamic_pricing_data['dynamic_price'] * dynamic_pricing_data['Item_Quantity']

# compare total sales amount between existing and dynamic pricing
total_sales_existing = data['Sales_Amount'].sum()
total_sales_dynamic = dynamic_pricing_data['dynamic_sales_amt'].sum()

# compare total quantity sold between existing and dynamic pricing
total_qty_existing = data['Item_Quantity'].sum()
total_qty_dynamic = dynamic_pricing_data['Item_Quantity'].sum()  # quantity sold remains the same for comparison

comparison_summary = pd.DataFrame({
    'Metric': ['Total Sales Amount', 'Total Quantity Sold'],
    'Existing Pricing': [total_sales_existing, total_qty_existing],
    'Dynamic Pricing': [total_sales_dynamic, total_qty_dynamic]
})

comparison_summary

data['dynamic_price'] = dynamic_pricing_data['dynamic_price']

"""Price Recommendation Engine Using Elasticity"""

def recommend_price(row):
    if pd.isna(row['elasticity']):
        return row['Price']
    elif row['elasticity'] < -1:
        return row['Price'] * 0.95  # decrease by 5%
    elif row['elasticity'] > -1 and row['elasticity'] < 0:
        return row['Price'] * 1.05  # increase by 5%
    else:
        return row['Price']

data['recommended_price'] = data.apply(recommend_price, axis=1)

plt.figure(figsize=(12, 6))
plt.plot(data['Fiscal_Week_ID'], data['Price'], label='Original Price', alpha=0.6)
plt.plot(data['Fiscal_Week_ID'], data['recommended_price'], label='Recommended Price', alpha=0.8)
plt.title('Original vs Recommended Prices Over Time')
plt.xlabel('Fiscal Week')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.show()

"""Sales Prediction Using Random Forest"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Encode segment
data['segment_encoded'] = data['segment'].astype('category').cat.codes

# Features & target
features = ['Price', 'Competition_Price', 'segment_encoded']
X = data[features]
y = data['Item_Quantity']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predict and evaluate
y_pred = model.predict(X_test)
# The 'squared' parameter is removed here and replaced with taking the square root of MSE
rmse = mean_squared_error(y_test, y_pred)**0.5
print(f"RMSE: {rmse:.2f}")

importances = model.feature_importances_
plt.barh(features, importances)
plt.title("Feature Importance in Sales Prediction")
plt.xlabel("Importance")
plt.grid(True)
plt.show()

"""A/B Testing Simulation for Dynamic vs Static Prices"""

def ab_test_simulation(data, test_fraction=0.3):
    test_group = data.sample(frac=test_fraction, random_state=42)
    control_group = data.drop(test_group.index)

    test_group['ab_price'] = test_group['recommended_price']
    control_group['ab_price'] = control_group['Price']

    test_group['ab_sales'] = test_group['ab_price'] * test_group['Item_Quantity']
    control_group['ab_sales'] = control_group['ab_price'] * control_group['Item_Quantity']

    summary = pd.DataFrame({
        'Group': ['Control', 'Test'],
        'Total Sales': [control_group['ab_sales'].sum(), test_group['ab_sales'].sum()],
        'Average Sales per Item': [control_group['ab_sales'].mean(), test_group['ab_sales'].mean()]
    })
    return summary

ab_test_result = ab_test_simulation(data)
print(ab_test_result)

"""Elasticity Heatmap by Segment and Price Bracket"""

heatmap_data = data.pivot_table(values='elasticity',
                                index='segment',
                                columns='price_bracket',
                                aggfunc='mean')

plt.figure(figsize=(10, 6))
sns.heatmap(heatmap_data, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Elasticity Heatmap by Segment and Price Bracket')
plt.show()

"""Profit Optimization Instead of Just Sales"""

# Assuming a cost estimate (you can replace this with actual cost per item)
data['estimated_cost'] = data['Price'] * 0.6  # 40% margin assumed

# Existing profit
data['profit'] = (data['Price'] - data['estimated_cost']) * data['Item_Quantity']

# Dynamic profit
data['dynamic_profit'] = (data['recommended_price'] - data['estimated_cost']) * data['Item_Quantity']

# Summary
profit_comparison = pd.DataFrame({
    'Metric': ['Total Profit'],
    'Original': [data['profit'].sum()],
    'Recommended Pricing': [data['dynamic_profit'].sum()]
})
print(profit_comparison)

labels = ['Original', 'Recommended']
profits = [data['profit'].sum(), data['dynamic_profit'].sum()]
plt.bar(labels, profits, color=['skyblue', 'orange'])
plt.title("Profit Comparison: Original vs Recommended Pricing")
plt.ylabel("Total Profit")
plt.show()

"""Add Seasonal or External Effects (Holidays, Weather, Trends)"""

# Create week_of_year feature
data['week_of_year'] = data['Fiscal_Week_ID'].dt.isocalendar().week

# Tag holiday season — modify as needed based on region/industry
holiday_weeks = [51, 52, 1, 2]  # peak festive/shopping weeks
data['is_holiday_season'] = data['week_of_year'].isin(holiday_weeks)

# Aggregate for visualization
holiday_agg = data.groupby('is_holiday_season').agg({
    'Price': 'mean',
    'Item_Quantity': 'mean'
}).reset_index()

holiday_agg['Season'] = holiday_agg['is_holiday_season'].map({True: 'Holiday Season', False: 'Regular Weeks'})

# Plot
fig, ax1 = plt.subplots(figsize=(10, 6))

ax2 = ax1.twinx()

ax1.bar(holiday_agg['Season'], holiday_agg['Item_Quantity'], width=0.4, color='skyblue', label='Avg Quantity Sold')
ax2.plot(holiday_agg['Season'], holiday_agg['Price'], color='orange', marker='o', linewidth=2, label='Avg Price')

ax1.set_ylabel('Avg Quantity Sold', color='skyblue')
ax2.set_ylabel('Avg Price', color='orange')

plt.title("Holiday Season vs Regular Weeks: Price & Quantity Sold")
fig.tight_layout()

# Legend
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines + lines2, labels + labels2, loc='upper right')

plt.grid(True)
plt.show()

"""Scenario Simulator Tool"""

# Sample elasticity (use segment/item-specific value if available)
avg_elasticity = data['elasticity'].mean()

# Create a range of price changes
price_changes = np.arange(-0.3, 0.31, 0.05)  # -30% to +30%

# Reference price and cost (assume one item or mean values)
base_price = data['Price'].mean()
cost = base_price * 0.6  # Assuming 40% margin

sim_results = []

for change in price_changes:
    new_price = base_price * (1 + change)
    pct_qty_change = avg_elasticity * change
    new_qty = data['Item_Quantity'].mean() * (1 + pct_qty_change)
    revenue = new_price * new_qty
    profit = (new_price - cost) * new_qty
    sim_results.append({
        'Price Change (%)': round(change * 100),
        'New Price': new_price,
        'Expected Quantity': new_qty,
        'Revenue': revenue,
        'Profit': profit
    })

scenario_df = pd.DataFrame(sim_results)

# Plot Revenue and Profit vs Price Change
fig, ax = plt.subplots(figsize=(12, 6))
sns.lineplot(x='Price Change (%)', y='Revenue', data=scenario_df, label='Revenue', marker='o')
sns.lineplot(x='Price Change (%)', y='Profit', data=scenario_df, label='Profit', marker='o', color='green')
plt.axvline(0, color='gray', linestyle='--', linewidth=1)
plt.title('Scenario Simulator: Impact of Price Changes on Revenue and Profit')
plt.xlabel('Price Change (%)')
plt.ylabel('Value')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""Trendline & Forecast (Optional)"""

from prophet import Prophet

df_prophet = weekly_prices[['Fiscal_Week_ID', 'Price']]
df_prophet.columns = ['ds', 'y']

model = Prophet()
model.fit(df_prophet)

future = model.make_future_dataframe(periods=12, freq='W')
forecast = model.predict(future)

model.plot(forecast)
plt.title("Forecasted Price Trend")
plt.show()